apiVersion: v1
kind: Service
metadata:
  name: {{ include "echothink.fullname" . }}-authentik
  namespace: {{ include "echothink.namespace" . }}
  labels:
    {{- include "echothink.componentLabels" (dict "ctx" . "component" "authentik-server") | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
    - port: 443
      targetPort: https
      protocol: TCP
      name: https
  selector:
    {{- include "echothink.componentSelectorLabels" (dict "ctx" . "component" "authentik-server") | nindent 4 }}
