apiVersion: v1
kind: Service
metadata:
  name: {{ include "echothink.fullname" . }}-minio
  namespace: {{ include "echothink.namespace" . }}
  labels:
    {{- include "echothink.componentLabels" (dict "ctx" . "component" "minio") | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 9000
      targetPort: api
      protocol: TCP
      name: api
    - port: 9001
      targetPort: console
      protocol: TCP
      name: console
  selector:
    {{- include "echothink.componentSelectorLabels" (dict "ctx" . "component" "minio") | nindent 4 }}
