apiVersion: v1
kind: Secret
metadata:
  name: {{ include "echothink.fullname" . }}-gitlab
  namespace: {{ include "echothink.namespace" . }}
  labels:
    {{- include "echothink.componentLabels" (dict "ctx" . "component" "gitlab") | nindent 4 }}
type: Opaque
data:
  root-password: {{ "changeme-gitlab-root" | b64enc | quote }}
